name: "xLink Client"
version: "0.0.6"
slug: xlink_client
description: "WireGuard client to connect to gateway and forward traffic to app"
arch:
  - aarch64
  - amd64
#  - i386
init: false
#startup: services
#boot: auto
#host_network: false
#capabilities:
#  - NET_ADMIN
map:
  - share:rw
options:
  GATEWAY_HOST: "gateway.your-domain.org"
  GATEWAY_PORT: 51823
  GATEWAY_PUBKEY: ""
  CLIENT_PRIVKEY: ""
  EXPOSE: "host.docker.internal:8123"
  LINK_MTU: 1380
  message: "Hello bubub ..."
schema:
  GATEWAY_HOST: str
  GATEWAY_PORT: int
  GATEWAY_PUBKEY: str
  CLIENT_PRIVKEY: str
  EXPOSE: str
  LINK_MTU: int
  message: "str?"
