name: "xLink Client"
version: "0.0.1"
slug: xlink_client
description: "WireGuard client to connect to gateway and forward traffic to app"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
boot: auto
host_network: false
capabilities:
  - NET_ADMIN
options:
  GATEWAY_HOST: "gateway.your-domain.org"
  GATEWAY_PORT: 51823
  GATEWAY_PUBKEY: ""
  CLIENT_PRIVKEY: ""
  EXPOSE: "host.docker.internal:8123"
  LINK_MTU: 1380
schema:
  GATEWAY_HOST: str
  GATEWAY_PORT: int
  GATEWAY_PUBKEY: str
  CLIENT_PRIVKEY: str
  EXPOSE: str
  LINK_MTU: int
